name: weather_new
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # use svg images in this project
  flutter_svg: ^1.1.4
  # additional features for this project
  html: ^0.15.0
  intl: ^0.17.0
  http: ^0.13.4
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  path_provider: ^2.0.11
  cupertino_icons: ^1.0.2
  dynamic_themes: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Black.ttf
          weight: 900
          style: normal
        - asset: fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
          style: normal
        - asset: fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
          style: normal
        - asset: fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
          style: normal
        - asset: fonts/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Roboto-Light.ttf
          weight: 300
          style: normal
        - asset: fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Roboto-Thin.ttf
          weight: 100
          style: normal
        - asset: fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
